name: gdlibrary_c_1239
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  pdf: ^3.6.4
  printing: ^5.9.0
  image_picker: ^1.0.4
  intl: ^0.17.0
  barcode_widget: ^2.0.4
  uuid: ^3.0.6
  responsive_sizer: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logo.png

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Regular.ttf
          style: italic
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
          
  uses-material-design: true
